default:
  image: python:3.9

stages:
  - lint

 before_script:
   - pip install flake8

flake8:
  stage: lint
  script:
    - python --version
    - pip install flake8
    - flake8 src/
  
  black_check:
    stage: lint
    scripts: 
      -black --chech --config pyproject.toml .
