default:
  image: python:3.9

stages:
  - linting

 before_script:
   - pip install flake8

flake8:
  stage: linting
  script:
    - flake8 --verbose .
  
  black:
    stage: linting
    scripts: 
      -black --chech --verbose --line-length 79 --skip-string-normalization -- .
