default:
  image: python:3.9

stages:
  - lint
  - test
  - deploy

 before_script:
   - pip install flake8

flake8:
  stage: lint
  script:
    - python --version
    - pip install flake8
    - flake8 src/



test:
  stage: test
  script:
    - echo python manage.py test
  only:
    - merge_requests

deploy:
  stage: deploy
  script:
    - echo "It's a good day to deploy"
  only:
    - merge_requests