# Generated by Django 4.2.5 on 2023-11-08 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.TextField(default=None, verbose_name="имя"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.TextField(
                choices=[
                    ("IN", "в обработке"),
                    ("GET", "получено"),
                    ("ANS", "ответ дан"),
                ],
                default="IN",
                verbose_name="статус обработки",
            ),
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время"
                    ),
                ),
                (
                    "from_status",
                    models.TextField(
                        choices=[
                            ("IN", "в обработке"),
                            ("GET", "в обработке"),
                            ("ANS", "ответ дан"),
                        ],
                        verbose_name="статус обработки",
                    ),
                ),
                (
                    "to",
                    models.TextField(
                        choices=[
                            ("IN", "в обработке"),
                            ("GET", "в обработке"),
                            ("ANS", "ответ дан"),
                        ],
                        verbose_name="статус обработки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
    ]
