# Generated by Django 4.2.5 on 2023-11-09 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0002_feedback_name_feedback_status_statuslog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Фидбек",
                "verbose_name_plural": "Фидбеки",
            },
        ),
        migrations.AlterModelOptions(
            name="statuslog",
            options={
                "verbose_name": "Лог изменения",
                "verbose_name_plural": "Лог изменений",
            },
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to",
            field=models.TextField(
                choices=[
                    ("IN", "в обработке"),
                    ("GET", "в обработке"),
                    ("ANS", "ответ дан"),
                ],
                db_column="to",
                verbose_name="статус обработки",
            ),
        ),
        migrations.RenameField(
            model_name="statuslog",
            old_name="to",
            new_name="to_status",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.TextField(blank=True, null=True, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.TextField(
                choices=[
                    ("IN", "в обработке"),
                    ("GET", "получено"),
                    ("ANS", "ответ дан"),
                ],
                default="GET",
                verbose_name="статус обработки",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.TextField(
                choices=[
                    ("IN", "в обработке"),
                    ("GET", "в обработке"),
                    ("ANS", "ответ дан"),
                ],
                db_column="from",
                verbose_name="статус обработки",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
