# Generated by Django 4.2.5 on 2023-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "feedback",
            "0003_alter_feedback_options_alter_statuslog_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.TextField(
                choices=[
                    ("IN", "в обработке"),
                    ("GET", "получено"),
                    ("ANS", "ответ дан"),
                ],
                db_column="from",
                verbose_name="старый статус обработки",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to_status",
            field=models.TextField(
                choices=[
                    ("IN", "в обработке"),
                    ("GET", "получено"),
                    ("ANS", "ответ дан"),
                ],
                db_column="to",
                verbose_name="новый статус обработки",
            ),
        ),
    ]
