# Generated by Django 4.2.5 on 2023-11-10 15:41

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "feedback",
            "0006_author_remove_feedback_mail_remove_feedback_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.author",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfile",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="feedback.feedback",
                verbose_name="фидбек файла",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfile",
            name="file",
            field=models.FileField(
                default=None,
                upload_to=feedback.models.FeedbackFile.file_directory_path,
                verbose_name="file",
            ),
        ),
    ]
