# Generated by Django 4.2.5 on 2023-11-14 12:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.Profile.upload_path,
                verbose_name="аватарка",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="coffee_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="выпито кофе"
            ),
        ),
    ]
