# Generated by Django 4.2.5 on 2023-11-02 11:55

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0001_squashed_0002_alter_category_normilized_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="normilized_name",
            field=models.CharField(
                editable=False,
                max_length=150,
                unique=True,
                verbose_name="Нормализоваванное имя",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="normilized_name",
            field=models.CharField(
                editable=False,
                max_length=150,
                unique=True,
                verbose_name="Нормализоваванное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normilized_name",
            field=models.CharField(
                editable=False,
                max_length=150,
                unique=True,
                verbose_name="Нормализоваванное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.TextField(
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(200),
                    django.core.validators.RegexValidator(
                        regex="[-a-zA-Z\\d_]+"
                    ),
                ],
                verbose_name="слаг",
            ),
        ),
        migrations.CreateModel(
            name="MainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        upload_to=catalog.models.item_directory_path,
                        verbose_name="image",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_image",
                        to="catalog.item",
                        verbose_name="Главное изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "главное изображение",
                "verbose_name_plural": "главные изображения",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        upload_to=catalog.models.item_directory_path,
                        verbose_name="image",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото",
                "verbose_name_plural": "фото",
            },
        ),
    ]
