# Generated by Django 4.2.5 on 2023-11-02 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_category_id_alter_category_normilized_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                default=None, to="catalog.tag", verbose_name="теги"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.TextField(
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(200),
                    django.core.validators.RegexValidator(regex="[-a-zA-Z\\d_]+"),
                ],
                verbose_name="слаг",
            ),
        ),
    ]
