# Generated by Django 4.2.5 on 2023-11-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_item_tags_alter_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False, verbose_name="на главной"
            ),
        ),
    ]
