# Generated by Django 4.2.5 on 2023-11-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_item_is_on_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_category",
                related_query_name="item",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
    ]
